# Copyright (c) 2019-2021, Jonas Eschle, Jim Pivarski, Eduardo Rodrigues, and Henry Schreiner.
#
# Distributed under the 3-clause BSD license, see accompanying file LICENSE
# or https://github.com/scikit-hep/vector for details.
from __future__ import annotations

import pytest

# The comparison of vector's results against ROOT's is a work in progress: many
# coordinate systems still disagree with ROOT on edge cases (degenerate inputs,
# wrap-around angles, sign of zero, nan/inf handling). Until those are resolved,
# the affected test functions are marked xfail so the suite stays green while
# still exercising the cases that already match.
#
# These are marked non-strict because only *some* parametrizations of each
# listed function fail; the rest pass (and report as XPASS). As discrepancies
# are fixed, drop the corresponding entry — once a function fully matches ROOT,
# removing it restores a hard PASS/FAIL signal.
KNOWN_FAILING = {
    "test_Polar2DVector": {
        "test_Mag",
        "test_Phi",
        "test_Rotate",
        "test_Unit",
        "test_add",
        "test_mul",
        "test_neg",
        "test_sub",
        "test_truediv",
    },
    "test_Polar3DVector": {
        "test_Cross",
        "test_Dot",
        "test_Mag2",
        "test_Perp2",
        "test_R",
        "test_Rho",
        "test_RotateX",
        "test_RotateY",
        "test_RotateZ",
        "test_Unit",
        "test_RotateAxes",
        "test_X_Y_Z",
        "test_add",
        "test_mul",
        "test_neg",
        "test_sub",
        "test_truediv",
    },
    "test_PtEtaPhiEVector": {
        "test_Beta",
        "test_Dot",
        "test_Eta",
        "test_Gamma",
        "test_M",
        "test_M2",
        "test_Mt",
        "test_Mt2",
        "test_P",
        "test_P2",
        "test_Perp",
        "test_Phi",
        "test_Rapidity",
        "test_RotateX",
        "test_RotateY",
        "test_RotateZ",
        "test_T",
        "test_Theta",
        "test_Z",
        "test_add",
        "test_eq",
        "test_isLightlike",
        "test_isSpacelike",
        "test_mul",
        "test_neg",
        "test_sub",
        "test_truediv",
    },
    "test_PtEtaPhiMVector": {
        "test_Beta",
        "test_Dot",
        "test_Eta",
        "test_Gamma",
        "test_M",
        "test_M2",
        "test_Mt",
        "test_Mt2",
        "test_P",
        "test_P2",
        "test_Perp",
        "test_Phi",
        "test_Rapidity",
        "test_RotateX",
        "test_RotateY",
        "test_RotateZ",
        "test_T",
        "test_Theta",
        "test_Z",
        "test_add",
        "test_eq",
        "test_isLightlike",
        "test_isTimelike",
        "test_mul",
        "test_neg",
        "test_sub",
        "test_truediv",
    },
    "test_PxPyPzEVector": {
        "test_Beta",
        "test_Dot",
        "test_Eta",
        "test_Gamma",
        "test_M",
        "test_M2",
        "test_Mt",
        "test_Mt2",
        "test_P",
        "test_P2",
        "test_Perp",
        "test_Perp2",
        "test_Phi",
        "test_Rapidity",
        "test_RotateX",
        "test_RotateY",
        "test_RotateZ",
        "test_T",
        "test_Theta",
        "test_X",
        "test_Y",
        "test_Z",
        "test_add",
        "test_eq",
        "test_isLightlike",
        "test_isSpacelike",
        "test_isTimelike",
        "test_mul",
        "test_neg",
        "test_sub",
        "test_truediv",
    },
    "test_PxPyPzMVector": {
        "test_Beta",
        "test_Dot",
        "test_Eta",
        "test_Gamma",
        "test_M",
        "test_M2",
        "test_Mt",
        "test_Mt2",
        "test_P",
        "test_P2",
        "test_Perp",
        "test_Perp2",
        "test_Phi",
        "test_Rapidity",
        "test_RotateX",
        "test_RotateY",
        "test_RotateZ",
        "test_T",
        "test_Theta",
        "test_X",
        "test_Y",
        "test_Z",
        "test_add",
        "test_eq",
        "test_isLightlike",
        "test_isSpacelike",
        "test_isTimelike",
        "test_mul",
        "test_neg",
        "test_sub",
        "test_truediv",
    },
    "test_RhoEtaPhiVector": {
        "test_Dot",
        "test_Mag2",
        "test_R",
        "test_RotateX",
        "test_RotateY",
        "test_RotateZ",
        "test_Unit",
        "test_add",
        "test_mul",
        "test_neg",
        "test_truediv",
    },
    "test_RhoZPhiVector": {
        "test_Dot",
        "test_Mag2",
        "test_Phi",
        "test_R",
        "test_RotateX",
        "test_RotateY",
        "test_RotateZ",
        "test_Unit",
        "test_X_and_Y",
        "test_add",
        "test_eq",
        "test_mul",
        "test_neg",
        "test_sub",
        "test_truediv",
    },
    "test_XYZVector": {"test_Eta", "test_Mag", "test_Mag2", "test_Perp", "test_Theta"},
    "test_vector": {"test_M2"},
}


def pytest_collection_modifyitems(items):
    for item in items:
        funcs = KNOWN_FAILING.get(item.path.stem)
        if funcs and item.originalname in funcs:
            item.add_marker(
                pytest.mark.xfail(
                    reason="ROOT comparison is a work in progress", strict=False
                )
            )
