name: Notebooks

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # The "FORCE_COLOR" variable, when set to 1,
  # tells Nox to colorize itself.
  FORCE_COLOR: "1"

jobs:
  test:
    name: Test notebooks
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"

      - name: List installed Python packages
        run: python -m pip list

      - name: Test example notebooks
        run: pipx run nox -s notebooks
